#:kivy 1.9.0
<CampApp>:
    RLMap:
        canvas:
            Color:
                rgba: 0, 0, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
    TileWidget:
        size_hint: None, None
        pos_hint: None

    PlaceholderActorWidget:
        size_hint: None, None
        canvas:
            Color:
                rgba: 1, 0, 0, 1
            Ellipse:
                size: self.size